replicaCount: 1
appName: frontend-service
imageName: gcr.io/google-samples/microservices-demo/frontend
appVersion: v0.2.3
containerPort: 8080
containerEnvVars:
- name: "PORT"
  value: "8080"
- name: "PRODUCT_CATALOG_SERVICE_ADDR"
  value: "catalog-service:3550"
- name: "CURRENCY_SERVICE_ADDR"
  value: "currency-service:7000"
- name: "CART_SERVICE_ADDR"
  value: "cart-service:7070"
- name: "RECOMMENDATION_SERVICE_ADDR"
  value: "recommendation-service:8080"
- name: "CHECKOUT_SERVICE_ADDR"
  value: "checkout-service:5050"
- name: "SHIPPING_SERVICE_ADDR"
  value: "shipping-service:50051"
- name: "AD_SERVICE_ADDR"
  value: "adservice-service:9555"
  
serviceType: LoadBalancer
servicePort: 80
