replicaCount: 1
appName: recommendation-service
imageName: gcr.io/google-samples/microservices-demo/recommendationservice
appVersion: v0.2.3
containerPort: 8080
containerEnvVars:
- name: "PORT"
  value: "8080"
- name: "PRODUCT_CATALOG_SERVICE_ADDR"
  value: "catalog-service:3550"
  
serviceType: ClusterIP
servicePort: 8080