replicaCount: 1
appName: shipping-service
imageName: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.2.3
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"
  
serviceType: ClusterIP
servicePort: 50051
